# Generated by Django 4.1.7 on 2023-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('idProducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=120)),
                ('precioUnitario', models.IntegerField()),
                ('cpu', models.CharField(max_length=5)),
                ('ram', models.IntegerField()),
                ('hdd', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('idProducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=120)),
                ('precioUnitario', models.IntegerField()),
                ('resolucion', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('idProducto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=120)),
                ('precioUnitario', models.IntegerField()),
                ('wireless', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.TextField()),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('compraMouse', models.ManyToManyField(blank=True, to='app_comercio.mouse')),
            ],
        ),
    ]
